### ISSUE TITLE
Не соотвествует критериям

### ISSUE THREAD

**Issue by denis-gr** [Se623/calc-lite-http#1]

**Comment by rptl8sr** [comment]
Запускается, работает, но:
1) нету тестов
2) разбить по пакетам надо
3) описание запуска всё-таки делается не абстрактное, а конкретное для этого проекта

**Comment by Barsenick** [comment]
> Запускается, работает, но:
> 
> 1. нету тестов
> 2. разбить по пакетам надо
> 3. описание запуска всё-таки делается не абстрактное, а конкретное для этого проекта

хотел сказать то же самое
Можно просто сделать папки как и в первом уроке спринта для разбиения по пакетам

**Comment by Se623** [comment]
Сделал

**Comment by Barsenick** [comment]
Исправил балл

**Comment by rptl8sr** [comment]
_Исправил балл_

Аналогично)
